# Generated by Django 3.0.5 on 2020-04-15 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('co', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SP', models.CharField(max_length=200)),
                ('j', models.CharField(max_length=200)),
                ('bo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoyo.name')),
            ],
        ),
    ]
